* biographys
** Jim Fowler
Jim Fowler teaches mathematics at The Ohio State University.  His
research interests broadly include geometry and topology, and more
specifically, his interests focus on the topology of high-dimensional
manifolds and geometric group theory, which means he gets to think
about highly symmetric (and therefore very beautiful) geometric
objects.  He's particularly fond of using computational techniques to
attack problems in pure mathematics.

Prior to OSU, he received an undergraduate degree from Harvard
University and received a Ph.D. from the University of Chicago.
** Steve Gubkin

** Bart Snapp
Bart Snapp teaches mathematics at The Ohio State University.  His
research interests include commutative ring theory, number theory, and
recreational mathematics.  He enjoys exploring connections between
mathematics and the real-world problems, art, and music. As an
undergraduate, he was involved in distance teaching and learning
though OSU's CROSU (Calculus Remote at Ohio State University) program.

Prior to OSU, he worked at Coastal Carolina University. Bart earned
his Ph.D. from the University Illinois at Urbana-Champaign. 
** Roman Holowinsky

Roman Holowinsky has been a professor in the OSU math department since
Fall of 2010.  His research in the field of analytic number theory
with a focus on L-functions and modular forms.  Roman is an Alfred
P. Sloan fellow and the recipient of the 2011 SASTRA Ramanujan prize.
For more information see http://www.math.osu.edu/~holowinsky.1
