* More aggressive online features?

- forum features
- youtube live for office hours
- calculus call-in show
- google voice phone number (call me at 773-809-5659, leave a message)
- khan academy style exercises

* What is the desired name of your class? 

Calculus One (I think this is nice to have One spelled out, like the
Statistics One course in Coursera already, or Air Force One)

* What is the desired shortname for your course?
calculus1

* Write a short 1-2 sentence (<200 character) course description.

Calculus One is a first introduction to differential and integral
calculus.



* How many hours per week can your students expect to spend on this class including videos and assignments?
6 - 10 hours per week?

* Write a 1-2 paragraph description of your course. 

Calculus is about the very large, the very small, and how things
change.  The surprise is that something seemingly so abstract ends up
explaining the real world: calculus plays a starring role in the
biological, physical, and social sciences.

This course is a first introduction to calculus, ideal for someone who
has never seen the subject before or for someone who wants a careful
review.  The course features
- interactive graphs to provide intuition,
- instant feedback on practice problems,
- 


This course is a first introduction to 

This course is a first
introduction

- clear, patient explanations
- five to fifteen minute videos
- emphasizing mastery
- instant feedback on homework
- individual tutoring

Mostly about differential calculus.

the introduction and use of Taylor series and approximations from the beginning;
a novel synthesis of discrete and continuous forms of Calculus;
an emphasis on the conceptual over the computational; and
a clear, entertaining, unified approach.



Emphasis on 



* Write a 1-2 paragraph bio about yourself.

Jim Fowler teaches mathematics at The Ohio State University.  Broadly
speaking, he is a geometer and topologist; more specifically, he
studies the topology of high-dimensional manifolds and geometric group
theory.  

 in other words, his research considers the symmetries of
objects with many degrees of freedom.  Prior to OSU, he received an
undergraduate degree from Harvard University and received a Ph.D. from
the University of Chicago.

* Please write a brief sentence that will explain each week's (or module's) topic. We will be asking for a syllabus from you later

* Write a paragraph briefly explaining the format of your course. 

The course consists of short lecture videos, typically between five
and fifteen minutes in length.  There are homework assignments, three
midterms, and a final exam.

* Write 1-2 paragraphs about any prerequisite background that students should have in order to succeed in your course. 

Previous exposure to calculus is not expected; to succeed, a student
should have seen algebra and trigonometry at the high school level.

* If applicable, provide a list of suggested readings in advance.

There are free calculus texts available, for example,

http://www.whitman.edu/mathematics/calculus/

but presumably I could take that text and produce a version with more
interactive figures and such, using, say, the lovely tufte class.

* Write your answer to suggested Frequently Asked Question (FAQ) #1: What resources will I need for this class?

Mathematics is a human activity; pen and paper is highly recommended.  You do not need a graphing calculator.

* Write your answer to suggested FAQ #2: What is the coolest thing I'll learn if I take this class?

When you push the square root button, how does the calculator do that?

* Write any additional FAQs and their responses that may be specific to your course.

Will I get a certificate after completing this class?

Yes.  Students who successfully complete the class will receive a certificate signed by the instructor.

* As a response to students signing up for your class, please write a welcoming email to the students who click on the "Take Class" button on your class course description page.

Dear [Student Name],

Thank you for signing up for Calculus One.

Calculus has changed the world: by providing a systematic way to
understand how things change, it has permitted humans to explain
the motions of heavenly bodies, 

Calculus can change you: the word "mathematics" comes from the same
word as "discipline."  Doing mathematics will train you to think
carefully, and precisely.  And it's a lot of fun.

I am looking forward to having you in the class.  I'll notify you
again in January 2013 to begin our time together.

thank you,
~jim

* Finally, as the course begins, an additional welcome email is sent to students in your course. Please write an email that welcomes them to the start of the class and explains the structure of the course, expectations, initial action steps for the students, a thank you for embarking on the journey of your course, etc.

Dear [Student Name],

Welcome to Calculus One.

You can now access the course at www.coursera.org/course/calculus1

Calculus is very old, but this is a very new way of presenting it.

You are pioneering both an emerging field and a novel form of online
learning. My teaching team and I have done our best to create a
substantive and engaging experience. We'll do everything we can to
make the course run smoothly, but bear with us -- this is all new!

If you have not yet filled out the informational survey, please do so
at [http://COURSESITE-SURVEY-LINK]. This will provide useful
information on who is taking the course. I encourage you to consider
yourself an active participant in this course.

Gamification is a subject that is developing quickly in the real
world. In some aspects it is uncertain or controversial today. The
course will give you a foundation to understand what gamification is
and how to apply it. The rest is up to you. Thank you for joining me
on this adventure!

~jim
